/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePlanDto,
  PlanAdminControllerFindAllParams,
  PlanEntity,
  UpdatePlanDto
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Создаёт тарифный план. Доступно только ADMIN.
 * @summary Создать план
 */
export const planAdminControllerCreate = (
    createPlanDto: BodyType<CreatePlanDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PlanEntity>(
      {url: `/api/admin/plans`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanDto, signal
    },
      options);
    }



export const getPlanAdminControllerCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planAdminControllerCreate>>, TError,{data: BodyType<CreatePlanDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof planAdminControllerCreate>>, TError,{data: BodyType<CreatePlanDto>}, TContext> => {

const mutationKey = ['planAdminControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof planAdminControllerCreate>>, {data: BodyType<CreatePlanDto>}> = (props) => {
          const {data} = props ?? {};

          return  planAdminControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PlanAdminControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof planAdminControllerCreate>>>
    export type PlanAdminControllerCreateMutationBody = BodyType<CreatePlanDto>
    export type PlanAdminControllerCreateMutationError = ErrorType<unknown>

    /**
 * @summary Создать план
 */
export const usePlanAdminControllerCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planAdminControllerCreate>>, TError,{data: BodyType<CreatePlanDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof planAdminControllerCreate>>,
        TError,
        {data: BodyType<CreatePlanDto>},
        TContext
      > => {
      return useMutation(getPlanAdminControllerCreateMutationOptions(options));
    }
    /**
 * Возвращает планы в формате, совместимом с React Admin: list и getMany.
 * @summary Получить список планов
 */
export const planAdminControllerFindAll = (
    params?: PlanAdminControllerFindAllParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PlanEntity[]>(
      {url: `/api/admin/plans`, method: 'GET',
        params, signal
    },
      options);
    }




export const getPlanAdminControllerFindAllQueryKey = (params?: PlanAdminControllerFindAllParams,) => {
    return [
    `/api/admin/plans`, ...(params ? [params] : [])
    ] as const;
    }


export const getPlanAdminControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof planAdminControllerFindAll>>, TError = ErrorType<unknown>>(params?: PlanAdminControllerFindAllParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof planAdminControllerFindAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlanAdminControllerFindAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof planAdminControllerFindAll>>> = ({ signal }) => planAdminControllerFindAll(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof planAdminControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type PlanAdminControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof planAdminControllerFindAll>>>
export type PlanAdminControllerFindAllQueryError = ErrorType<unknown>


/**
 * @summary Получить список планов
 */

export function usePlanAdminControllerFindAll<TData = Awaited<ReturnType<typeof planAdminControllerFindAll>>, TError = ErrorType<unknown>>(
 params?: PlanAdminControllerFindAllParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof planAdminControllerFindAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPlanAdminControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const planAdminControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PlanEntity>(
      {url: `/api/admin/plans/${id}`, method: 'GET', signal
    },
      options);
    }




export const getPlanAdminControllerFindOneQueryKey = (id: string,) => {
    return [
    `/api/admin/plans/${id}`
    ] as const;
    }


export const getPlanAdminControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof planAdminControllerFindOne>>, TError = ErrorType<unknown>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof planAdminControllerFindOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlanAdminControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof planAdminControllerFindOne>>> = ({ signal }) => planAdminControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof planAdminControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type PlanAdminControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof planAdminControllerFindOne>>>
export type PlanAdminControllerFindOneQueryError = ErrorType<unknown>



export function usePlanAdminControllerFindOne<TData = Awaited<ReturnType<typeof planAdminControllerFindOne>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof planAdminControllerFindOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPlanAdminControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Обновляет тарифный план. Доступно только ADMIN.
 * @summary Обновить план
 */
export const planAdminControllerUpdate = (
    id: string,
    updatePlanDto: BodyType<UpdatePlanDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PlanEntity>(
      {url: `/api/admin/plans/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updatePlanDto, signal
    },
      options);
    }



export const getPlanAdminControllerUpdateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planAdminControllerUpdate>>, TError,{id: string;data: BodyType<UpdatePlanDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof planAdminControllerUpdate>>, TError,{id: string;data: BodyType<UpdatePlanDto>}, TContext> => {

const mutationKey = ['planAdminControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof planAdminControllerUpdate>>, {id: string;data: BodyType<UpdatePlanDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  planAdminControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PlanAdminControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof planAdminControllerUpdate>>>
    export type PlanAdminControllerUpdateMutationBody = BodyType<UpdatePlanDto>
    export type PlanAdminControllerUpdateMutationError = ErrorType<unknown>

    /**
 * @summary Обновить план
 */
export const usePlanAdminControllerUpdate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planAdminControllerUpdate>>, TError,{id: string;data: BodyType<UpdatePlanDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof planAdminControllerUpdate>>,
        TError,
        {id: string;data: BodyType<UpdatePlanDto>},
        TContext
      > => {
      return useMutation(getPlanAdminControllerUpdateMutationOptions(options));
    }
    export const planAdminControllerRemove = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PlanEntity>(
      {url: `/api/admin/plans/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getPlanAdminControllerRemoveMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planAdminControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof planAdminControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['planAdminControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof planAdminControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  planAdminControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PlanAdminControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof planAdminControllerRemove>>>

    export type PlanAdminControllerRemoveMutationError = ErrorType<unknown>

    export const usePlanAdminControllerRemove = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planAdminControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof planAdminControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPlanAdminControllerRemoveMutationOptions(options));
    }
