/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ResetSubscribeDto,
  SubscribeBuyDto,
  SubscribeEntity,
  UpdateSubscribeDto
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const subscribeControllerBuy = (
    subscribeBuyDto: BodyType<SubscribeBuyDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/subscriptions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: subscribeBuyDto, signal
    },
      options);
    }



export const getSubscribeControllerBuyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeControllerBuy>>, TError,{data: BodyType<SubscribeBuyDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof subscribeControllerBuy>>, TError,{data: BodyType<SubscribeBuyDto>}, TContext> => {

const mutationKey = ['subscribeControllerBuy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subscribeControllerBuy>>, {data: BodyType<SubscribeBuyDto>}> = (props) => {
          const {data} = props ?? {};

          return  subscribeControllerBuy(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubscribeControllerBuyMutationResult = NonNullable<Awaited<ReturnType<typeof subscribeControllerBuy>>>
    export type SubscribeControllerBuyMutationBody = BodyType<SubscribeBuyDto>
    export type SubscribeControllerBuyMutationError = ErrorType<unknown>

    export const useSubscribeControllerBuy = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeControllerBuy>>, TError,{data: BodyType<SubscribeBuyDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof subscribeControllerBuy>>,
        TError,
        {data: BodyType<SubscribeBuyDto>},
        TContext
      > => {
      return useMutation(getSubscribeControllerBuyMutationOptions(options), queryClient);
    }
    /**
 * Возвращает список подписок текущего пользователя.
 * @summary Получить мои подписки
 */
export const subscribeControllerFindAll = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SubscribeEntity[]>(
      {url: `/api/subscriptions`, method: 'GET', signal
    },
      options);
    }




export const getSubscribeControllerFindAllQueryKey = () => {
    return [
    `/api/subscriptions`
    ] as const;
    }


export const getSubscribeControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof subscribeControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSubscribeControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof subscribeControllerFindAll>>> = ({ signal }) => subscribeControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof subscribeControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SubscribeControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof subscribeControllerFindAll>>>
export type SubscribeControllerFindAllQueryError = ErrorType<unknown>


export function useSubscribeControllerFindAll<TData = Awaited<ReturnType<typeof subscribeControllerFindAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscribeControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof subscribeControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubscribeControllerFindAll<TData = Awaited<ReturnType<typeof subscribeControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscribeControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof subscribeControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubscribeControllerFindAll<TData = Awaited<ReturnType<typeof subscribeControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить мои подписки
 */

export function useSubscribeControllerFindAll<TData = Awaited<ReturnType<typeof subscribeControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSubscribeControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const subscribeControllerResetSubscribe = (
    resetSubscribeDto: BodyType<ResetSubscribeDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/subscriptions/reset`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetSubscribeDto, signal
    },
      options);
    }



export const getSubscribeControllerResetSubscribeMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeControllerResetSubscribe>>, TError,{data: BodyType<ResetSubscribeDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof subscribeControllerResetSubscribe>>, TError,{data: BodyType<ResetSubscribeDto>}, TContext> => {

const mutationKey = ['subscribeControllerResetSubscribe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subscribeControllerResetSubscribe>>, {data: BodyType<ResetSubscribeDto>}> = (props) => {
          const {data} = props ?? {};

          return  subscribeControllerResetSubscribe(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubscribeControllerResetSubscribeMutationResult = NonNullable<Awaited<ReturnType<typeof subscribeControllerResetSubscribe>>>
    export type SubscribeControllerResetSubscribeMutationBody = BodyType<ResetSubscribeDto>
    export type SubscribeControllerResetSubscribeMutationError = ErrorType<unknown>

    export const useSubscribeControllerResetSubscribe = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeControllerResetSubscribe>>, TError,{data: BodyType<ResetSubscribeDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof subscribeControllerResetSubscribe>>,
        TError,
        {data: BodyType<ResetSubscribeDto>},
        TContext
      > => {
      return useMutation(getSubscribeControllerResetSubscribeMutationOptions(options), queryClient);
    }
    /**
 * Возвращает одну подписку текущего пользователя.
 * @summary Получить подписку по id
 */
export const subscribeControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SubscribeEntity>(
      {url: `/api/subscriptions/${id}`, method: 'GET', signal
    },
      options);
    }




export const getSubscribeControllerFindOneQueryKey = (id: number,) => {
    return [
    `/api/subscriptions/${id}`
    ] as const;
    }


export const getSubscribeControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof subscribeControllerFindOne>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSubscribeControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof subscribeControllerFindOne>>> = ({ signal }) => subscribeControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof subscribeControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SubscribeControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof subscribeControllerFindOne>>>
export type SubscribeControllerFindOneQueryError = ErrorType<unknown>


export function useSubscribeControllerFindOne<TData = Awaited<ReturnType<typeof subscribeControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscribeControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof subscribeControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubscribeControllerFindOne<TData = Awaited<ReturnType<typeof subscribeControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscribeControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof subscribeControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubscribeControllerFindOne<TData = Awaited<ReturnType<typeof subscribeControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить подписку по id
 */

export function useSubscribeControllerFindOne<TData = Awaited<ReturnType<typeof subscribeControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribeControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSubscribeControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Обновляет подписку. Доступно только ADMIN.
 * @summary Обновить подписку
 */
export const subscribeControllerUpdate = (
    id: number,
    updateSubscribeDto: BodyType<UpdateSubscribeDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SubscribeEntity>(
      {url: `/api/subscriptions/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSubscribeDto, signal
    },
      options);
    }



export const getSubscribeControllerUpdateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeControllerUpdate>>, TError,{id: number;data: BodyType<UpdateSubscribeDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof subscribeControllerUpdate>>, TError,{id: number;data: BodyType<UpdateSubscribeDto>}, TContext> => {

const mutationKey = ['subscribeControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subscribeControllerUpdate>>, {id: number;data: BodyType<UpdateSubscribeDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  subscribeControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubscribeControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof subscribeControllerUpdate>>>
    export type SubscribeControllerUpdateMutationBody = BodyType<UpdateSubscribeDto>
    export type SubscribeControllerUpdateMutationError = ErrorType<unknown>

    /**
 * @summary Обновить подписку
 */
export const useSubscribeControllerUpdate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeControllerUpdate>>, TError,{id: number;data: BodyType<UpdateSubscribeDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof subscribeControllerUpdate>>,
        TError,
        {id: number;data: BodyType<UpdateSubscribeDto>},
        TContext
      > => {
      return useMutation(getSubscribeControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * Удаляет подписку текущего пользователя.
 * @summary Удалить подписку
 */
export const subscribeControllerRemove = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/subscriptions/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getSubscribeControllerRemoveMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof subscribeControllerRemove>>, TError,{id: number}, TContext> => {

const mutationKey = ['subscribeControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subscribeControllerRemove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  subscribeControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubscribeControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof subscribeControllerRemove>>>

    export type SubscribeControllerRemoveMutationError = ErrorType<unknown>

    /**
 * @summary Удалить подписку
 */
export const useSubscribeControllerRemove = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof subscribeControllerRemove>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getSubscribeControllerRemoveMutationOptions(options), queryClient);
    }
