/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePlanDto,
  PlanEntity,
  UpdatePlanDto
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Создаёт тарифный план. Доступно только ADMIN.
 * @summary Создать план
 */
export const planControllerCreate = (
    createPlanDto: BodyType<CreatePlanDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PlanEntity>(
      {url: `/api/plans`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanDto, signal
    },
      options);
    }



export const getPlanControllerCreateMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planControllerCreate>>, TError,{data: BodyType<CreatePlanDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof planControllerCreate>>, TError,{data: BodyType<CreatePlanDto>}, TContext> => {

const mutationKey = ['planControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof planControllerCreate>>, {data: BodyType<CreatePlanDto>}> = (props) => {
          const {data} = props ?? {};

          return  planControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PlanControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof planControllerCreate>>>
    export type PlanControllerCreateMutationBody = BodyType<CreatePlanDto>
    export type PlanControllerCreateMutationError = ErrorType<void>

    /**
 * @summary Создать план
 */
export const usePlanControllerCreate = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planControllerCreate>>, TError,{data: BodyType<CreatePlanDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof planControllerCreate>>,
        TError,
        {data: BodyType<CreatePlanDto>},
        TContext
      > => {
      return useMutation(getPlanControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * Возвращает публичный список тарифных планов.
 * @summary Получить список планов
 */
export const planControllerFindAll = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PlanEntity[]>(
      {url: `/api/plans`, method: 'GET', signal
    },
      options);
    }




export const getPlanControllerFindAllQueryKey = () => {
    return [
    `/api/plans`
    ] as const;
    }


export const getPlanControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof planControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof planControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlanControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof planControllerFindAll>>> = ({ signal }) => planControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof planControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PlanControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof planControllerFindAll>>>
export type PlanControllerFindAllQueryError = ErrorType<unknown>


export function usePlanControllerFindAll<TData = Awaited<ReturnType<typeof planControllerFindAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof planControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof planControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof planControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlanControllerFindAll<TData = Awaited<ReturnType<typeof planControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof planControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof planControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof planControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlanControllerFindAll<TData = Awaited<ReturnType<typeof planControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof planControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить список планов
 */

export function usePlanControllerFindAll<TData = Awaited<ReturnType<typeof planControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof planControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPlanControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Возвращает один тарифный план по идентификатору.
 * @summary Получить план по id
 */
export const planControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PlanEntity>(
      {url: `/api/plans/${id}`, method: 'GET', signal
    },
      options);
    }




export const getPlanControllerFindOneQueryKey = (id: number,) => {
    return [
    `/api/plans/${id}`
    ] as const;
    }


export const getPlanControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof planControllerFindOne>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof planControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlanControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof planControllerFindOne>>> = ({ signal }) => planControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof planControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PlanControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof planControllerFindOne>>>
export type PlanControllerFindOneQueryError = ErrorType<unknown>


export function usePlanControllerFindOne<TData = Awaited<ReturnType<typeof planControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof planControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof planControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof planControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlanControllerFindOne<TData = Awaited<ReturnType<typeof planControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof planControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof planControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof planControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlanControllerFindOne<TData = Awaited<ReturnType<typeof planControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof planControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить план по id
 */

export function usePlanControllerFindOne<TData = Awaited<ReturnType<typeof planControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof planControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPlanControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Обновляет тарифный план. Доступно только ADMIN.
 * @summary Обновить план
 */
export const planControllerUpdate = (
    id: number,
    updatePlanDto: BodyType<UpdatePlanDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PlanEntity>(
      {url: `/api/plans/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePlanDto, signal
    },
      options);
    }



export const getPlanControllerUpdateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planControllerUpdate>>, TError,{id: number;data: BodyType<UpdatePlanDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof planControllerUpdate>>, TError,{id: number;data: BodyType<UpdatePlanDto>}, TContext> => {

const mutationKey = ['planControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof planControllerUpdate>>, {id: number;data: BodyType<UpdatePlanDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  planControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PlanControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof planControllerUpdate>>>
    export type PlanControllerUpdateMutationBody = BodyType<UpdatePlanDto>
    export type PlanControllerUpdateMutationError = ErrorType<unknown>

    /**
 * @summary Обновить план
 */
export const usePlanControllerUpdate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planControllerUpdate>>, TError,{id: number;data: BodyType<UpdatePlanDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof planControllerUpdate>>,
        TError,
        {id: number;data: BodyType<UpdatePlanDto>},
        TContext
      > => {
      return useMutation(getPlanControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * Удаляет тарифный план. Доступно только ADMIN.
 * @summary Удалить план
 */
export const planControllerRemove = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PlanEntity>(
      {url: `/api/plans/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getPlanControllerRemoveMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof planControllerRemove>>, TError,{id: number}, TContext> => {

const mutationKey = ['planControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof planControllerRemove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  planControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PlanControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof planControllerRemove>>>

    export type PlanControllerRemoveMutationError = ErrorType<unknown>

    /**
 * @summary Удалить план
 */
export const usePlanControllerRemove = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof planControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof planControllerRemove>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPlanControllerRemoveMutationOptions(options), queryClient);
    }
