/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PlanEntity
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Возвращает публичный список тарифных планов.
 * @summary Получить список планов
 */
export const planControllerFindAll = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PlanEntity[]>(
      {url: `/api/plans`, method: 'GET', signal
    },
      options);
    }




export const getPlanControllerFindAllQueryKey = () => {
    return [
    `/api/plans`
    ] as const;
    }


export const getPlanControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof planControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof planControllerFindAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlanControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof planControllerFindAll>>> = ({ signal }) => planControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof planControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type PlanControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof planControllerFindAll>>>
export type PlanControllerFindAllQueryError = ErrorType<unknown>


/**
 * @summary Получить список планов
 */

export function usePlanControllerFindAll<TData = Awaited<ReturnType<typeof planControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof planControllerFindAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPlanControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Возвращает один тарифный план по идентификатору.
 * @summary Получить план по id
 */
export const planControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PlanEntity>(
      {url: `/api/plans/${id}`, method: 'GET', signal
    },
      options);
    }




export const getPlanControllerFindOneQueryKey = (id: number,) => {
    return [
    `/api/plans/${id}`
    ] as const;
    }


export const getPlanControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof planControllerFindOne>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof planControllerFindOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlanControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof planControllerFindOne>>> = ({ signal }) => planControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof planControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type PlanControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof planControllerFindOne>>>
export type PlanControllerFindOneQueryError = ErrorType<unknown>


/**
 * @summary Получить план по id
 */

export function usePlanControllerFindOne<TData = Awaited<ReturnType<typeof planControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof planControllerFindOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPlanControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






