/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  WalletControllerGetMyWalletParams
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const walletControllerGetMyWallet = (
    params: WalletControllerGetMyWalletParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/wallets/my`, method: 'GET',
        params, signal
    },
      options);
    }




export const getWalletControllerGetMyWalletQueryKey = (params?: WalletControllerGetMyWalletParams,) => {
    return [
    `/api/wallets/my`, ...(params ? [params] : [])
    ] as const;
    }


export const getWalletControllerGetMyWalletQueryOptions = <TData = Awaited<ReturnType<typeof walletControllerGetMyWallet>>, TError = ErrorType<unknown>>(params: WalletControllerGetMyWalletParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof walletControllerGetMyWallet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWalletControllerGetMyWalletQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof walletControllerGetMyWallet>>> = ({ signal }) => walletControllerGetMyWallet(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof walletControllerGetMyWallet>>, TError, TData> & { queryKey: QueryKey }
}

export type WalletControllerGetMyWalletQueryResult = NonNullable<Awaited<ReturnType<typeof walletControllerGetMyWallet>>>
export type WalletControllerGetMyWalletQueryError = ErrorType<unknown>



export function useWalletControllerGetMyWallet<TData = Awaited<ReturnType<typeof walletControllerGetMyWallet>>, TError = ErrorType<unknown>>(
 params: WalletControllerGetMyWalletParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof walletControllerGetMyWallet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWalletControllerGetMyWalletQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






