/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
export interface Decimal2 { [key: string]: unknown }

export interface PlanEntity {
  discountedPercent: Decimal2;
  /** @nullable */
  features: string | null;
  isSpecial: boolean;
  isDiscounted: boolean;
  /** @nullable */
  pluses: string | null;
  id: number;
  name: string;
  price: number;
  /** @nullable */
  description?: string | null;
  totalGb: number;
  duratationDays: number;
}

export interface CreatePlanDto {
  isSpecial: boolean;
  discountedPercent: Decimal2;
  /** @nullable */
  features: string | null;
  totalGb: number;
  price: number;
  description: string;
  inboundId: number;
  name: string;
  duratationDays: number;
}

export interface Object { [key: string]: unknown }

export interface UpdatePlanDto {
  isSpecial?: boolean;
  discountedPercent?: Decimal2;
  /** @nullable */
  features?: string | null;
  totalGb?: number;
  price?: number;
  description?: string;
  inboundId?: number;
  name?: string;
  duratationDays?: number;
}

export type LoginAuthenticatedResponseDtoType = typeof LoginAuthenticatedResponseDtoType[keyof typeof LoginAuthenticatedResponseDtoType];


export const LoginAuthenticatedResponseDtoType = {
  AUTHENTICATED: 'AUTHENTICATED',
} as const;

export interface LoginAuthenticatedResponseDto {
  type: LoginAuthenticatedResponseDtoType;
}

export type LoginTotpRequiredResponseDtoType = typeof LoginTotpRequiredResponseDtoType[keyof typeof LoginTotpRequiredResponseDtoType];


export const LoginTotpRequiredResponseDtoType = {
  TOTP_REQUIRED: 'TOTP_REQUIRED',
} as const;

export interface LoginTotpRequiredResponseDto {
  type: LoginTotpRequiredResponseDtoType;
  challengeId: string;
}

export type AcceptedPolicyDtoType = typeof AcceptedPolicyDtoType[keyof typeof AcceptedPolicyDtoType];


export const AcceptedPolicyDtoType = {
  PRIVACY: 'PRIVACY',
  PUBLIC: 'PUBLIC',
  TERMS: 'TERMS',
} as const;

export interface AcceptedPolicyDto {
  version: string;
  type: AcceptedPolicyDtoType;
}

export interface LoginDto {
  login: string;
  password: string;
  policy: AcceptedPolicyDto[];
}

export interface RegisterDto {
  login: string;
  password: string;
}

export interface LoginTotpValidateDto {
  challengeId: string;
  vallue: string;
}

export interface SessionEntity {
  /** Session ID — уникальный идентификатор сессии */
  sid: string;
  /** User ID — идентификатор пользователя (CUID) */
  uid: string;
  /** Last Activity Timestamp — время последней активности в миллисекундах */
  lat: number;
  /** User Agent — строка с User-Agent клиента */
  ua: string;
  /** Client Type — тип клиента (например, web, mobile, api) */
  ct: string;
  cat: number;
  isCurrent: boolean;
}

export type PolicyEntityType = typeof PolicyEntityType[keyof typeof PolicyEntityType];


export const PolicyEntityType = {
  PRIVACY: 'PRIVACY',
  PUBLIC: 'PUBLIC',
  TERMS: 'TERMS',
} as const;

export interface PolicyEntity {
  id: number;
  type: PolicyEntityType;
  version: string;
  content: string;
}

export interface TotpValidateDto {
  /** UUID challenge, полученный из `POST /totp/setup`. */
  challengeId: string;
  /**
     * 6-значный TOTP код из приложения-аутентификатора.
     * @pattern ^\d{6}$
     */
  value: string;
}

export interface TotpRemoveDto {
  /**
     * 6-значный TOTP код для подтверждения отключения двухфакторной аутентификации.
     * @pattern ^\d{6}$
     */
  value: string;
}

export interface CreateInboundDto {
  inboundId: number;
  name: string;
  enable: boolean;
}

export interface UpdateInboundDto {
  inboundId?: number;
  name?: string;
  enable?: boolean;
}

export interface XuiClient {
  /** UUID клиента в x-ui */
  id?: string;
  /** Email/label клиента в x-ui */
  email?: string;
  /** Sub ID клиента в x-ui */
  subId?: string;
  /** Flow (обычно пустая строка для большинства случаев) */
  flow: string;
  /** Лимит одновременных IP (0 = без ограничения) */
  limitIp: number;
  /** Общий трафик в байтах (0 = без лимита) */
  totalGB: number;
  /** Время истечения в миллисекундах (timestamp). 0 = без срока */
  expiryTime: number;
  /** Включен ли клиент */
  enable: boolean;
  /** Telegram ID */
  tgId: string;
  /** Комментарий */
  comment: string;
  /** Reset (обычно 0) */
  reset: number;
}

export interface WalletEntity {
  id: string;
  held: number;
  balance: number;
}

export type UserEntityRole = typeof UserEntityRole[keyof typeof UserEntityRole];


export const UserEntityRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;

export interface UserEntity {
  id: string;
  login: string;
  /** @nullable */
  telegramId: number | null;
  isBanned: boolean;
  role: UserEntityRole;
  createdAt: string;
  updatedAt: string;
  canComment: boolean;
  wallet?: WalletEntity | null;
  walletId: string;
}

export interface PatchMeDto { [key: string]: unknown }

export type UpdateUserDtoRole = typeof UpdateUserDtoRole[keyof typeof UpdateUserDtoRole];


export const UpdateUserDtoRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;

export interface UpdateUserDto {
  role?: UpdateUserDtoRole;
  telegramId?: number;
  login?: string;
  isBanned?: boolean;
  canComment?: boolean;
}

export interface CreatePaymentDto {
  /** Сумма пополнения в рублях строкой. */
  amount: string;
}

export type PaymentEntityStatus = typeof PaymentEntityStatus[keyof typeof PaymentEntityStatus];


export const PaymentEntityStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  WAITING_FOR_CONFIRMATION: 'WAITING_FOR_CONFIRMATION',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  CANCELED: 'CANCELED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
} as const;

export interface PaymentEntity {
  id: number;
  providerPaymentId: string;
  status: PaymentEntityStatus;
  currency: string;
  value: number;
  createdAt: string;
  /** @nullable */
  description: string | null;
  userId: string;
  confirmationUrl: string;
  /** @nullable */
  planId: string | null;
}

export interface GiveBonusDto {
  /** Идентификатор пользователя. */
  userId: string;
  /** Сумма бонуса в минимальных единицах (копейки). */
  amount: number;
}

export interface CreditWalletDto { [key: string]: unknown }

export interface DebitWalletDto { [key: string]: unknown }

export interface CreateWalletDto {
  /** @minimum 0 */
  held?: number;
  /** @minimum 0 */
  balance?: number;
}

export interface UpdateWalletDto {
  /** @minimum 0 */
  held?: number;
  /** @minimum 0 */
  balance?: number;
}

export interface SubscribeBuyDto {
  planId: number;
  deviceName: string;
  policy: AcceptedPolicyDto[];
}

export interface ResetSubscribeDto {
  subscribeId: string;
}

export type SubscribeEntityStatus = typeof SubscribeEntityStatus[keyof typeof SubscribeEntityStatus];


export const SubscribeEntityStatus = {
  STOPPED: 'STOPPED',
  ACTIVE: 'ACTIVE',
  PENDING: 'PENDING',
} as const;

export interface SubscribeEntity {
  userId: string;
  email: string;
  name: string;
  id: string;
  lenght: number;
  vlessClientId: string;
  nextPaymentDate: string;
  status: SubscribeEntityStatus;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
  planId: number;
  totalGb: number;
}

export interface UpdateSubscribeDto {
  name: string;
}

export interface ClientTypeExistDto {
  clientTypeName: string;
}

export type PlanAdminControllerFindAllParams = {
/**
 * JSON-массив вида [field, order]
 */
sort?: string[];
/**
 * JSON-массив вида [start, end]
 */
range?: string[];
/**
 * JSON-объект фильтра
 */
filter?: Object;
/**
 * JSON-массив embed-полей
 */
embed?: string;
};

export type PolicyControllerGetActualParams = {
/**
 * Тип юридического документа.
 */
type?: PolicyControllerGetActualType;
};

export type PolicyControllerGetActualType = typeof PolicyControllerGetActualType[keyof typeof PolicyControllerGetActualType];


export const PolicyControllerGetActualType = {
  PRIVACY: 'PRIVACY',
  PUBLIC: 'PUBLIC',
  TERMS: 'TERMS',
} as const;

export type UserAdminControllerGetAllParams = {
/**
 * JSON-массив вида [field, order]
 */
sort?: string[];
/**
 * JSON-массив вида [start, end]
 */
range?: string[];
/**
 * JSON-объект фильтра
 */
filter?: Object;
/**
 * JSON-массив embed-полей
 */
embed?: string;
};

export type WalletControllerGetMyWalletParams = {
id: string;
};

export type WalletAdminControllerFindAllParams = {
/**
 * JSON-массив вида [field, order]
 */
sort?: string[];
/**
 * JSON-массив вида [start, end]
 */
range?: string[];
/**
 * JSON-объект фильтра
 */
filter?: Object;
/**
 * JSON-массив embed-полей
 */
embed?: string;
};

