/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
export type Decimal2 = { [key: string]: unknown };

export type PlanEntity = {
  discountedPercent: Decimal2;
  /** @nullable */
  features: string | null;
  isSpecial: boolean;
  isDiscounted: boolean;
  /** @nullable */
  pluses: string | null;
  id: number;
  name: string;
  price: number;
  /** @nullable */
  description?: string | null;
  totalGb: number;
  duratationDays: number;
};

export type CreatePlanDto = {
  isSpecial: boolean;
  discountedPercent: Decimal2;
  /** @nullable */
  features: string | null;
  totalGb: number;
  price: number;
  description: string;
  inboundId: number;
  name: string;
  duratationDays: number;
};

export type Object = { [key: string]: unknown };

export type UpdatePlanDto = {
  isSpecial?: boolean;
  discountedPercent?: Decimal2;
  /** @nullable */
  features?: string | null;
  totalGb?: number;
  price?: number;
  description?: string;
  inboundId?: number;
  name?: string;
  duratationDays?: number;
};

export type AcceptedPolicyDtoType = typeof AcceptedPolicyDtoType[keyof typeof AcceptedPolicyDtoType];


export const AcceptedPolicyDtoType = {
  PRIVACY: 'PRIVACY',
  PUBLIC: 'PUBLIC',
  TERMS: 'TERMS',
} as const;

export type AcceptedPolicyDto = {
  version: string;
  type: AcceptedPolicyDtoType;
};

export type IntersectionTotpRequestLoginDto = {
  /** TOTP verification code */
  token?: string;
  login: string;
  password: string;
  policy: AcceptedPolicyDto[];
};

export type RegisterDto = {
  login: string;
  password: string;
};

export type SessionEntity = {
  /** Session ID — уникальный идентификатор сессии */
  sid: string;
  /** User ID — идентификатор пользователя (CUID) */
  uid: string;
  /** Last Activity Timestamp — время последней активности в миллисекундах */
  lat: number;
  /** User Agent — строка с User-Agent клиента */
  ua: string;
  /** Client Type — тип клиента (например, web, mobile, api) */
  ct: string;
  cat: number;
  isCurrent: boolean;
};

export type PolicyEntityType = typeof PolicyEntityType[keyof typeof PolicyEntityType];


export const PolicyEntityType = {
  PRIVACY: 'PRIVACY',
  PUBLIC: 'PUBLIC',
  TERMS: 'TERMS',
} as const;

export type PolicyEntity = {
  id: number;
  type: PolicyEntityType;
  version: string;
  content: string;
};

export type CreateInboundDto = {
  inboundId: number;
  name: string;
  enable: boolean;
};

export type UpdateInboundDto = {
  inboundId?: number;
  name?: string;
  enable?: boolean;
};

export type XuiClient = {
  /** UUID клиента в x-ui */
  id?: string;
  /** Email/label клиента в x-ui */
  email?: string;
  /** Sub ID клиента в x-ui */
  subId?: string;
  /** Flow (обычно пустая строка для большинства случаев) */
  flow: string;
  /** Лимит одновременных IP (0 = без ограничения) */
  limitIp: number;
  /** Общий трафик в байтах (0 = без лимита) */
  totalGB: number;
  /** Время истечения в миллисекундах (timestamp). 0 = без срока */
  expiryTime: number;
  /** Включен ли клиент */
  enable: boolean;
  /** Telegram ID */
  tgId: string;
  /** Комментарий */
  comment: string;
  /** Reset (обычно 0) */
  reset: number;
};

export type WalletEntity = {
  id: string;
  held: number;
  balance: number;
};

export type UserEntityRole = typeof UserEntityRole[keyof typeof UserEntityRole];


export const UserEntityRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;

export type UserEntity = {
  id: string;
  login: string;
  /** @nullable */
  telegramId: number | null;
  isBanned: boolean;
  role: UserEntityRole;
  createdAt: string;
  updatedAt: string;
  canComment: boolean;
  /** @nullable */
  wallet?: WalletEntity | null;
  walletId: string;
};

export type PatchMeDto = { [key: string]: unknown };

export type UpdateUserDtoRole = typeof UpdateUserDtoRole[keyof typeof UpdateUserDtoRole];


export const UpdateUserDtoRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;

export type UpdateUserDto = {
  role?: UpdateUserDtoRole;
  telegramId?: number;
  login?: string;
  isBanned?: boolean;
  canComment?: boolean;
};

export type CreatePaymentDto = {
  /** Сумма пополнения в рублях строкой. */
  amount: string;
};

export type PaymentEntityStatus = typeof PaymentEntityStatus[keyof typeof PaymentEntityStatus];


export const PaymentEntityStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  WAITING_FOR_CONFIRMATION: 'WAITING_FOR_CONFIRMATION',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  CANCELED: 'CANCELED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
} as const;

export type PaymentEntity = {
  id: number;
  providerPaymentId: string;
  status: PaymentEntityStatus;
  currency: string;
  value: number;
  createdAt: string;
  /** @nullable */
  description: string | null;
  userId: string;
  confirmationUrl: string;
  /** @nullable */
  planId: string | null;
};

export type GiveBonusDto = {
  /** Идентификатор пользователя. */
  userId: string;
  /** Сумма бонуса в минимальных единицах (копейки). */
  amount: number;
};

export type CreditWalletDto = { [key: string]: unknown };

export type DebitWalletDto = { [key: string]: unknown };

export type CreateWalletDto = {
  /** @minimum 0 */
  held?: number;
  /** @minimum 0 */
  balance?: number;
};

export type UpdateWalletDto = {
  /** @minimum 0 */
  held?: number;
  /** @minimum 0 */
  balance?: number;
};

export type SubscribeBuyDto = {
  planId: number;
  deviceName: string;
  policy: AcceptedPolicyDto[];
};

export type ResetSubscribeDto = {
  subscribeId: string;
};

export type SubscribeEntityStatus = typeof SubscribeEntityStatus[keyof typeof SubscribeEntityStatus];


export const SubscribeEntityStatus = {
  STOPPED: 'STOPPED',
  ACTIVE: 'ACTIVE',
  PENDING: 'PENDING',
} as const;

export type SubscribeEntity = {
  userId: string;
  email: string;
  name: string;
  id: string;
  lenght: number;
  vlessClientId: string;
  nextPaymentDate: string;
  status: SubscribeEntityStatus;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
  planId: number;
  totalGb: number;
};

export type UpdateSubscribeDto = {
  name: string;
};

export type ClientTypeExistDto = {
  clientTypeName: string;
};

export type TotpSetupDto = { [key: string]: unknown };

export type IntersectionTotpRequestTotpToggleDto = {
  /** TOTP verification code */
  token?: string;
  status: boolean;
};

export type PlanAdminControllerFindAllParams = {
/**
 * JSON-массив вида [field, order]
 */
sort?: string[];
/**
 * JSON-массив вида [start, end]
 */
range?: string[];
/**
 * JSON-объект фильтра
 */
filter?: Object;
/**
 * JSON-массив embed-полей
 */
embed?: string;
};

export type PolicyControllerGetActualParams = {
/**
 * Тип юридического документа.
 */
type?: PolicyControllerGetActualType;
};

export type PolicyControllerGetActualType = typeof PolicyControllerGetActualType[keyof typeof PolicyControllerGetActualType];


export const PolicyControllerGetActualType = {
  PRIVACY: 'PRIVACY',
  PUBLIC: 'PUBLIC',
  TERMS: 'TERMS',
} as const;

export type UserAdminControllerGetAllParams = {
/**
 * JSON-массив вида [field, order]
 */
sort?: string[];
/**
 * JSON-массив вида [start, end]
 */
range?: string[];
/**
 * JSON-объект фильтра
 */
filter?: Object;
/**
 * JSON-массив embed-полей
 */
embed?: string;
};

export type WalletControllerGetMyWalletParams = {
id: string;
};

export type WalletAdminControllerFindAllParams = {
/**
 * JSON-массив вида [field, order]
 */
sort?: string[];
/**
 * JSON-массив вида [start, end]
 */
range?: string[];
/**
 * JSON-объект фильтра
 */
filter?: Object;
/**
 * JSON-массив embed-полей
 */
embed?: string;
};

