/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
export interface CreatePlanDto {
  price: number;
  description: string;
  inboundId: number;
  name: string;
  duratationDays: number;
}

/**
 * @nullable
 */
export type PlanEntityDescription = { [key: string]: unknown } | null;

export interface PlanEntity {
  id: number;
  name: string;
  price: number;
  /** @nullable */
  description?: PlanEntityDescription;
  totalGb: number;
  inboundId: number;
  duratationDays: number;
}

export interface UpdatePlanDto {
  price?: number;
  description?: string;
  inboundId?: number;
  name?: string;
  duratationDays?: number;
}

export interface LoginDto {
  login: string;
  password: string;
}

export interface RegisterDto {
  login: string;
  password: string;
}

export interface ClientTypeExistDto {
  clientTypeName: string;
}

export interface CreateInboundDto {
  inboundId: number;
  name: string;
  enable: boolean;
}

export interface UpdateInboundDto {
  inboundId?: number;
  name?: string;
  enable?: boolean;
}

export interface XuiClient {
  /** UUID клиента в x-ui */
  id?: string;
  /** Email/label клиента в x-ui */
  email?: string;
  /** Sub ID клиента в x-ui */
  subId?: string;
  /** Flow (обычно пустая строка для большинства случаев) */
  flow: string;
  /** Лимит одновременных IP (0 = без ограничения) */
  limitIp: number;
  /** Общий трафик в байтах (0 = без лимита) */
  totalGB: number;
  /** Время истечения в миллисекундах (timestamp). 0 = без срока */
  expiryTime: number;
  /** Включен ли клиент */
  enable: boolean;
  /** Telegram ID */
  tgId: string;
  /** Комментарий */
  comment: string;
  /** Reset (обычно 0) */
  reset: number;
}

export interface PatchMeDto { [key: string]: unknown }

export interface CreateRefundDto {
  /** Локальный идентификатор платежа в таблице payments. */
  paymentId: number;
}

export interface YookassaWebhookBaseDto { [key: string]: unknown }

export interface CreditWalletDto { [key: string]: unknown }

export interface DebitWalletDto { [key: string]: unknown }

export interface CreateReviewDto {
  /** Текст отзыва. */
  content: string;
  /**
     * Оценка от 1 до 5.
     * @minimum 1
     * @maximum 5
     */
  rating: number;
}

export interface CreatePaymentDto {
  /** Сумма пополнения в рублях строкой. */
  amount: string;
}

export interface GiveBonusDto {
  /** Идентификатор пользователя. */
  userId: string;
  /** Сумма бонуса в минимальных единицах (копейки). */
  amount: number;
}

export interface SubscribeBuyDto {
  planId: number;
  deviceName: string;
}

export interface ResetSubscribeDto {
  subscribeId: string;
}

export interface UpdateSubscribeDto { [key: string]: unknown }

