/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  YookassaWebhookBaseDto
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Принимает webhook от YooKassa и запускает локальную обработку платежного события.
 * @summary Webhook YooKassa
 */
export const yookassaControllerWebhook = (
    yookassaWebhookBaseDto: BodyType<YookassaWebhookBaseDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/yookassa/webhook`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: yookassaWebhookBaseDto, signal
    },
      options);
    }



export const getYookassaControllerWebhookMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof yookassaControllerWebhook>>, TError,{data: BodyType<YookassaWebhookBaseDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof yookassaControllerWebhook>>, TError,{data: BodyType<YookassaWebhookBaseDto>}, TContext> => {

const mutationKey = ['yookassaControllerWebhook'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof yookassaControllerWebhook>>, {data: BodyType<YookassaWebhookBaseDto>}> = (props) => {
          const {data} = props ?? {};

          return  yookassaControllerWebhook(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type YookassaControllerWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof yookassaControllerWebhook>>>
    export type YookassaControllerWebhookMutationBody = BodyType<YookassaWebhookBaseDto>
    export type YookassaControllerWebhookMutationError = ErrorType<void>

    /**
 * @summary Webhook YooKassa
 */
export const useYookassaControllerWebhook = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof yookassaControllerWebhook>>, TError,{data: BodyType<YookassaWebhookBaseDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof yookassaControllerWebhook>>,
        TError,
        {data: BodyType<YookassaWebhookBaseDto>},
        TContext
      > => {
      return useMutation(getYookassaControllerWebhookMutationOptions(options), queryClient);
    }
