events {}

http {
  server {
    listen 80;
    server_name zerokqx.ru www.zerokqx.ru;

    location = / {
      return 301 /vpn/;
    }

    location = /api {
      return 301 /api/;
    }

    location ^~ /api/ {
      proxy_pass http://127.0.0.1:4000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /vpn {
      return 301 /vpn/;
    }

    location ^~ /vpn/ {
      proxy_pass http://127.0.0.1:4200/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
