/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../../axios-client';
import type { ErrorType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Возвращает список сессий текущего пользователя.
 * @summary Получить мои сессии
 */
export const sessionControllerFindAll = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/sessions`, method: 'GET', signal
    },
      options);
    }




export const getSessionControllerFindAllQueryKey = () => {
    return [
    `/api/sessions`
    ] as const;
    }


export const getSessionControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof sessionControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSessionControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sessionControllerFindAll>>> = ({ signal }) => sessionControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SessionControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof sessionControllerFindAll>>>
export type SessionControllerFindAllQueryError = ErrorType<unknown>


export function useSessionControllerFindAll<TData = Awaited<ReturnType<typeof sessionControllerFindAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSessionControllerFindAll<TData = Awaited<ReturnType<typeof sessionControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSessionControllerFindAll<TData = Awaited<ReturnType<typeof sessionControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить мои сессии
 */

export function useSessionControllerFindAll<TData = Awaited<ReturnType<typeof sessionControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSessionControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Возвращает сессию, соответствующую текущему refresh-контексту.
 * @summary Получить текущую сессию
 */
export const sessionControllerCurrentUserSession = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/sessions/me`, method: 'GET', signal
    },
      options);
    }




export const getSessionControllerCurrentUserSessionQueryKey = () => {
    return [
    `/api/sessions/me`
    ] as const;
    }


export const getSessionControllerCurrentUserSessionQueryOptions = <TData = Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSessionControllerCurrentUserSessionQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>> = ({ signal }) => sessionControllerCurrentUserSession(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SessionControllerCurrentUserSessionQueryResult = NonNullable<Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>>
export type SessionControllerCurrentUserSessionQueryError = ErrorType<unknown>


export function useSessionControllerCurrentUserSession<TData = Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSessionControllerCurrentUserSession<TData = Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSessionControllerCurrentUserSession<TData = Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить текущую сессию
 */

export function useSessionControllerCurrentUserSession<TData = Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerCurrentUserSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSessionControllerCurrentUserSessionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Возвращает одну сессию текущего пользователя по идентификатору.
 * @summary Получить сессию по id
 */
export const sessionControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/sessions/${id}`, method: 'GET', signal
    },
      options);
    }




export const getSessionControllerFindOneQueryKey = (id: string,) => {
    return [
    `/api/sessions/${id}`
    ] as const;
    }


export const getSessionControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof sessionControllerFindOne>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSessionControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sessionControllerFindOne>>> = ({ signal }) => sessionControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SessionControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof sessionControllerFindOne>>>
export type SessionControllerFindOneQueryError = ErrorType<unknown>


export function useSessionControllerFindOne<TData = Awaited<ReturnType<typeof sessionControllerFindOne>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSessionControllerFindOne<TData = Awaited<ReturnType<typeof sessionControllerFindOne>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSessionControllerFindOne<TData = Awaited<ReturnType<typeof sessionControllerFindOne>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить сессию по id
 */

export function useSessionControllerFindOne<TData = Awaited<ReturnType<typeof sessionControllerFindOne>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSessionControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Удаляет сессию по id. Требует refresh cookie и x-client-type=web.
 * @summary Удалить сессию
 */
export const sessionControllerRemove = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/sessions/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getSessionControllerRemoveMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sessionControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sessionControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['sessionControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sessionControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  sessionControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SessionControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof sessionControllerRemove>>>

    export type SessionControllerRemoveMutationError = ErrorType<void>

    /**
 * @summary Удалить сессию
 */
export const useSessionControllerRemove = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sessionControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sessionControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getSessionControllerRemoveMutationOptions(options), queryClient);
    }
