export const COOKIE_NAME = {
  ACCESS: 'zeroquestAccess',
  REFRESH: 'zeroquestRefresh',
  CSRF: 'zeroquestCsrf',
} as const;

export const HEADERS_NAMES = {
  FINGERPRINT: 'x-client-fingerprint',
  CLIENT_TYPE: 'x-client-type',
  CSRF: 'x-csrf-token',
} as const;

export const RESPONSE_CODES = {
  AUTHENTICATED: 'AUTHENTICATED',
  AUTHENTICATED_FAILED_BECAUSE_USER_IS_BANNED:
    'AUTHENTICATED_FAILED_BECAUSE_USER_IS_BANNED',
  BANNED: 'BANNED',
  SESSION_NOT_EXISTS: 'SESSION_NOT_EXISTS',
  CSRF_INVALID: 'CSRF_INVALID',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOTP_REQUIRED: 'TOTP_REQUIRED',
  TOTP_CHALLENGE_NOT_FOUND:"TOTP_CHALLANGE_NOT_FOUND",
  TOTP_INVALID_CHALLANGE:"TOTP_INVALID_CHALLANGE"
};
