/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PolicyControllerGetActualParams,
  PolicyEntity
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Возвращает актуальную версию документа по типу или null, если документ отсутствует. Если type не передан, используется POLICY.
 * @summary Получить актуальный юридический документ
 */
export const policyControllerGetActual = (
    params?: PolicyControllerGetActualParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PolicyEntity>(
      {url: `/api/policy/actual`, method: 'GET',
        params, signal
    },
      options);
    }




export const getPolicyControllerGetActualQueryKey = (params?: PolicyControllerGetActualParams,) => {
    return [
    `/api/policy/actual`, ...(params ? [params] : [])
    ] as const;
    }


export const getPolicyControllerGetActualQueryOptions = <TData = Awaited<ReturnType<typeof policyControllerGetActual>>, TError = ErrorType<unknown>>(params?: PolicyControllerGetActualParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof policyControllerGetActual>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPolicyControllerGetActualQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof policyControllerGetActual>>> = ({ signal }) => policyControllerGetActual(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof policyControllerGetActual>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PolicyControllerGetActualQueryResult = NonNullable<Awaited<ReturnType<typeof policyControllerGetActual>>>
export type PolicyControllerGetActualQueryError = ErrorType<unknown>


export function usePolicyControllerGetActual<TData = Awaited<ReturnType<typeof policyControllerGetActual>>, TError = ErrorType<unknown>>(
 params: undefined |  PolicyControllerGetActualParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof policyControllerGetActual>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof policyControllerGetActual>>,
          TError,
          Awaited<ReturnType<typeof policyControllerGetActual>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePolicyControllerGetActual<TData = Awaited<ReturnType<typeof policyControllerGetActual>>, TError = ErrorType<unknown>>(
 params?: PolicyControllerGetActualParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof policyControllerGetActual>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof policyControllerGetActual>>,
          TError,
          Awaited<ReturnType<typeof policyControllerGetActual>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePolicyControllerGetActual<TData = Awaited<ReturnType<typeof policyControllerGetActual>>, TError = ErrorType<unknown>>(
 params?: PolicyControllerGetActualParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof policyControllerGetActual>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить актуальный юридический документ
 */

export function usePolicyControllerGetActual<TData = Awaited<ReturnType<typeof policyControllerGetActual>>, TError = ErrorType<unknown>>(
 params?: PolicyControllerGetActualParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof policyControllerGetActual>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPolicyControllerGetActualQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






