/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateInboundDto,
  UpdateInboundDto
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Создаёт inbound-конфигурацию. Доступно только ADMIN для web client type.
 * @summary Создать inbound
 */
export const inboundControllerCreate = (
    createInboundDto: BodyType<CreateInboundDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/inbounds`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createInboundDto, signal
    },
      options);
    }



export const getInboundControllerCreateMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inboundControllerCreate>>, TError,{data: BodyType<CreateInboundDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof inboundControllerCreate>>, TError,{data: BodyType<CreateInboundDto>}, TContext> => {

const mutationKey = ['inboundControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inboundControllerCreate>>, {data: BodyType<CreateInboundDto>}> = (props) => {
          const {data} = props ?? {};

          return  inboundControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InboundControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof inboundControllerCreate>>>
    export type InboundControllerCreateMutationBody = BodyType<CreateInboundDto>
    export type InboundControllerCreateMutationError = ErrorType<void>

    /**
 * @summary Создать inbound
 */
export const useInboundControllerCreate = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inboundControllerCreate>>, TError,{data: BodyType<CreateInboundDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inboundControllerCreate>>,
        TError,
        {data: BodyType<CreateInboundDto>},
        TContext
      > => {
      return useMutation(getInboundControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * Возвращает список всех inbound-конфигураций.
 * @summary Получить список inbound
 */
export const inboundControllerFindAll = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/inbounds`, method: 'GET', signal
    },
      options);
    }




export const getInboundControllerFindAllQueryKey = () => {
    return [
    `/api/inbounds`
    ] as const;
    }


export const getInboundControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof inboundControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inboundControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInboundControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof inboundControllerFindAll>>> = ({ signal }) => inboundControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inboundControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InboundControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof inboundControllerFindAll>>>
export type InboundControllerFindAllQueryError = ErrorType<unknown>


export function useInboundControllerFindAll<TData = Awaited<ReturnType<typeof inboundControllerFindAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inboundControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inboundControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof inboundControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInboundControllerFindAll<TData = Awaited<ReturnType<typeof inboundControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inboundControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inboundControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof inboundControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInboundControllerFindAll<TData = Awaited<ReturnType<typeof inboundControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inboundControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить список inbound
 */

export function useInboundControllerFindAll<TData = Awaited<ReturnType<typeof inboundControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inboundControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInboundControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Возвращает одну inbound-конфигурацию по внутреннему идентификатору.
 * @summary Получить inbound по id
 */
export const inboundControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/inbounds/${id}`, method: 'GET', signal
    },
      options);
    }




export const getInboundControllerFindOneQueryKey = (id: number,) => {
    return [
    `/api/inbounds/${id}`
    ] as const;
    }


export const getInboundControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof inboundControllerFindOne>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inboundControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInboundControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof inboundControllerFindOne>>> = ({ signal }) => inboundControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inboundControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InboundControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof inboundControllerFindOne>>>
export type InboundControllerFindOneQueryError = ErrorType<unknown>


export function useInboundControllerFindOne<TData = Awaited<ReturnType<typeof inboundControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inboundControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inboundControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof inboundControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInboundControllerFindOne<TData = Awaited<ReturnType<typeof inboundControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inboundControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inboundControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof inboundControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInboundControllerFindOne<TData = Awaited<ReturnType<typeof inboundControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inboundControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить inbound по id
 */

export function useInboundControllerFindOne<TData = Awaited<ReturnType<typeof inboundControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inboundControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInboundControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Обновляет inbound-конфигурацию по id.
 * @summary Обновить inbound
 */
export const inboundControllerUpdate = (
    id: number,
    updateInboundDto: BodyType<UpdateInboundDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/inbounds/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateInboundDto, signal
    },
      options);
    }



export const getInboundControllerUpdateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inboundControllerUpdate>>, TError,{id: number;data: BodyType<UpdateInboundDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof inboundControllerUpdate>>, TError,{id: number;data: BodyType<UpdateInboundDto>}, TContext> => {

const mutationKey = ['inboundControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inboundControllerUpdate>>, {id: number;data: BodyType<UpdateInboundDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  inboundControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InboundControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof inboundControllerUpdate>>>
    export type InboundControllerUpdateMutationBody = BodyType<UpdateInboundDto>
    export type InboundControllerUpdateMutationError = ErrorType<unknown>

    /**
 * @summary Обновить inbound
 */
export const useInboundControllerUpdate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inboundControllerUpdate>>, TError,{id: number;data: BodyType<UpdateInboundDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inboundControllerUpdate>>,
        TError,
        {id: number;data: BodyType<UpdateInboundDto>},
        TContext
      > => {
      return useMutation(getInboundControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * Удаляет inbound-конфигурацию по id.
 * @summary Удалить inbound
 */
export const inboundControllerRemove = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/inbounds/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getInboundControllerRemoveMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inboundControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof inboundControllerRemove>>, TError,{id: number}, TContext> => {

const mutationKey = ['inboundControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inboundControllerRemove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  inboundControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InboundControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof inboundControllerRemove>>>

    export type InboundControllerRemoveMutationError = ErrorType<unknown>

    /**
 * @summary Удалить inbound
 */
export const useInboundControllerRemove = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inboundControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inboundControllerRemove>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getInboundControllerRemoveMutationOptions(options), queryClient);
    }
