/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  TotpRemoveDto,
  TotpValidateDto
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Генерирует новый TOTP секрет, шифрует его и возвращает идентификатор challenge для последующей валидации кода.
 * @summary Создать TOTP challenge
 */
export const totpControllerSetup = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<string>(
      {url: `/api/totp/setup`, method: 'POST', signal
    },
      options);
    }



export const getTotpControllerSetupMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totpControllerSetup>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof totpControllerSetup>>, TError,void, TContext> => {

const mutationKey = ['totpControllerSetup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof totpControllerSetup>>, void> = () => {


          return  totpControllerSetup(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TotpControllerSetupMutationResult = NonNullable<Awaited<ReturnType<typeof totpControllerSetup>>>

    export type TotpControllerSetupMutationError = ErrorType<void>

    /**
 * @summary Создать TOTP challenge
 */
export const useTotpControllerSetup = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totpControllerSetup>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof totpControllerSetup>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getTotpControllerSetupMutationOptions(options));
    }
    /**
 * Проверяет введённый 6-значный TOTP код по challengeId и, если код валиден, привязывает TOTP к текущему пользователю.
 * @summary Подтвердить TOTP код
 */
export const totpControllerValidate = (
    totpValidateDto: BodyType<TotpValidateDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/totp/validate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: totpValidateDto, signal
    },
      options);
    }



export const getTotpControllerValidateMutationOptions = <TError = ErrorType<void | unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totpControllerValidate>>, TError,{data: BodyType<TotpValidateDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof totpControllerValidate>>, TError,{data: BodyType<TotpValidateDto>}, TContext> => {

const mutationKey = ['totpControllerValidate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof totpControllerValidate>>, {data: BodyType<TotpValidateDto>}> = (props) => {
          const {data} = props ?? {};

          return  totpControllerValidate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TotpControllerValidateMutationResult = NonNullable<Awaited<ReturnType<typeof totpControllerValidate>>>
    export type TotpControllerValidateMutationBody = BodyType<TotpValidateDto>
    export type TotpControllerValidateMutationError = ErrorType<void | unknown>

    /**
 * @summary Подтвердить TOTP код
 */
export const useTotpControllerValidate = <TError = ErrorType<void | unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totpControllerValidate>>, TError,{data: BodyType<TotpValidateDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof totpControllerValidate>>,
        TError,
        {data: BodyType<TotpValidateDto>},
        TContext
      > => {
      return useMutation(getTotpControllerValidateMutationOptions(options));
    }
    /**
 * Удаляет TOTP у текущего пользователя после подтверждения 6-значным кодом из приложения-аутентификатора.
 * @summary Отключить TOTP
 */
export const totpControllerRemove = (
    totpRemoveDto: BodyType<TotpRemoveDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/totp`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: totpRemoveDto, signal
    },
      options);
    }



export const getTotpControllerRemoveMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totpControllerRemove>>, TError,{data: BodyType<TotpRemoveDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof totpControllerRemove>>, TError,{data: BodyType<TotpRemoveDto>}, TContext> => {

const mutationKey = ['totpControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof totpControllerRemove>>, {data: BodyType<TotpRemoveDto>}> = (props) => {
          const {data} = props ?? {};

          return  totpControllerRemove(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TotpControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof totpControllerRemove>>>
    export type TotpControllerRemoveMutationBody = BodyType<TotpRemoveDto>
    export type TotpControllerRemoveMutationError = ErrorType<void>

    /**
 * @summary Отключить TOTP
 */
export const useTotpControllerRemove = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totpControllerRemove>>, TError,{data: BodyType<TotpRemoveDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof totpControllerRemove>>,
        TError,
        {data: BodyType<TotpRemoveDto>},
        TContext
      > => {
      return useMutation(getTotpControllerRemoveMutationOptions(options));
    }
