/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  IntersectionTotpRequestTotpToggleDto,
  TotpSetupDto
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Создает setup jwt cookie и возвращает uri для приложения.
 * @summary Setup TOTP
 */
export const totpControllerSetup = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/totp/setup`, method: 'POST', signal
    },
      options);
    }



export const getTotpControllerSetupMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totpControllerSetup>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof totpControllerSetup>>, TError,void, TContext> => {

const mutationKey = ['totpControllerSetup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof totpControllerSetup>>, void> = () => {


          return  totpControllerSetup(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TotpControllerSetupMutationResult = NonNullable<Awaited<ReturnType<typeof totpControllerSetup>>>

    export type TotpControllerSetupMutationError = ErrorType<unknown>

    /**
 * @summary Setup TOTP
 */
export const useTotpControllerSetup = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totpControllerSetup>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof totpControllerSetup>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getTotpControllerSetupMutationOptions(options));
    }
    /**
 * Проверяет код и сохраняет TOTP для пользователя.
 * @summary Validate setup TOTP
 */
export const totpControllerValidateSetup = (
    totpSetupDto: BodyType<TotpSetupDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/totp/setup/validate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: totpSetupDto, signal
    },
      options);
    }



export const getTotpControllerValidateSetupMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totpControllerValidateSetup>>, TError,{data: BodyType<TotpSetupDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof totpControllerValidateSetup>>, TError,{data: BodyType<TotpSetupDto>}, TContext> => {

const mutationKey = ['totpControllerValidateSetup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof totpControllerValidateSetup>>, {data: BodyType<TotpSetupDto>}> = (props) => {
          const {data} = props ?? {};

          return  totpControllerValidateSetup(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TotpControllerValidateSetupMutationResult = NonNullable<Awaited<ReturnType<typeof totpControllerValidateSetup>>>
    export type TotpControllerValidateSetupMutationBody = BodyType<TotpSetupDto>
    export type TotpControllerValidateSetupMutationError = ErrorType<unknown>

    /**
 * @summary Validate setup TOTP
 */
export const useTotpControllerValidateSetup = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totpControllerValidateSetup>>, TError,{data: BodyType<TotpSetupDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof totpControllerValidateSetup>>,
        TError,
        {data: BodyType<TotpSetupDto>},
        TContext
      > => {
      return useMutation(getTotpControllerValidateSetupMutationOptions(options));
    }
    /**
 * @summary Включает или выключает TOTP
 */
export const totpControllerDisableTotp = (
    intersectionTotpRequestTotpToggleDto: BodyType<IntersectionTotpRequestTotpToggleDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/totp/toggle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: intersectionTotpRequestTotpToggleDto, signal
    },
      options);
    }



export const getTotpControllerDisableTotpMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totpControllerDisableTotp>>, TError,{data: BodyType<IntersectionTotpRequestTotpToggleDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof totpControllerDisableTotp>>, TError,{data: BodyType<IntersectionTotpRequestTotpToggleDto>}, TContext> => {

const mutationKey = ['totpControllerDisableTotp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof totpControllerDisableTotp>>, {data: BodyType<IntersectionTotpRequestTotpToggleDto>}> = (props) => {
          const {data} = props ?? {};

          return  totpControllerDisableTotp(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TotpControllerDisableTotpMutationResult = NonNullable<Awaited<ReturnType<typeof totpControllerDisableTotp>>>
    export type TotpControllerDisableTotpMutationBody = BodyType<IntersectionTotpRequestTotpToggleDto>
    export type TotpControllerDisableTotpMutationError = ErrorType<unknown>

    /**
 * @summary Включает или выключает TOTP
 */
export const useTotpControllerDisableTotp = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totpControllerDisableTotp>>, TError,{data: BodyType<IntersectionTotpRequestTotpToggleDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof totpControllerDisableTotp>>,
        TError,
        {data: BodyType<IntersectionTotpRequestTotpToggleDto>},
        TContext
      > => {
      return useMutation(getTotpControllerDisableTotpMutationOptions(options));
    }
