/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateRefundDto,
  RefundEntity
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Создаёт локальную заявку на возврат в БД. Внешний запрос в YooKassa не отправляется.
 * @summary Создать заявку на возврат
 */
export const refundControllerCreate = (
    createRefundDto: BodyType<CreateRefundDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<RefundEntity>(
      {url: `/api/refunds`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRefundDto, signal
    },
      options);
    }



export const getRefundControllerCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refundControllerCreate>>, TError,{data: BodyType<CreateRefundDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refundControllerCreate>>, TError,{data: BodyType<CreateRefundDto>}, TContext> => {

const mutationKey = ['refundControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refundControllerCreate>>, {data: BodyType<CreateRefundDto>}> = (props) => {
          const {data} = props ?? {};

          return  refundControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefundControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof refundControllerCreate>>>
    export type RefundControllerCreateMutationBody = BodyType<CreateRefundDto>
    export type RefundControllerCreateMutationError = ErrorType<unknown>

    /**
 * @summary Создать заявку на возврат
 */
export const useRefundControllerCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refundControllerCreate>>, TError,{data: BodyType<CreateRefundDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refundControllerCreate>>,
        TError,
        {data: BodyType<CreateRefundDto>},
        TContext
      > => {
      return useMutation(getRefundControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * Админский эндпоинт. Возвращает все заявки на возврат из БД.
 * @summary Получить все заявки на возврат
 */
export const refundControllerFindAll = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<RefundEntity[]>(
      {url: `/api/refunds`, method: 'GET', signal
    },
      options);
    }




export const getRefundControllerFindAllQueryKey = () => {
    return [
    `/api/refunds`
    ] as const;
    }


export const getRefundControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof refundControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof refundControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRefundControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof refundControllerFindAll>>> = ({ signal }) => refundControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof refundControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RefundControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof refundControllerFindAll>>>
export type RefundControllerFindAllQueryError = ErrorType<unknown>


export function useRefundControllerFindAll<TData = Awaited<ReturnType<typeof refundControllerFindAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof refundControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof refundControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof refundControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRefundControllerFindAll<TData = Awaited<ReturnType<typeof refundControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof refundControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof refundControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof refundControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRefundControllerFindAll<TData = Awaited<ReturnType<typeof refundControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof refundControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить все заявки на возврат
 */

export function useRefundControllerFindAll<TData = Awaited<ReturnType<typeof refundControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof refundControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRefundControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Админский эндпоинт. Отправляет запрос на возврат в YooKassa и выставляет статус APPROVE.
 * @summary Подтвердить возврат
 */
export const refundControllerApprove = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/refunds/${id}/status/approved`, method: 'PATCH', signal
    },
      options);
    }



export const getRefundControllerApproveMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refundControllerApprove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refundControllerApprove>>, TError,{id: number}, TContext> => {

const mutationKey = ['refundControllerApprove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refundControllerApprove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  refundControllerApprove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefundControllerApproveMutationResult = NonNullable<Awaited<ReturnType<typeof refundControllerApprove>>>

    export type RefundControllerApproveMutationError = ErrorType<unknown>

    /**
 * @summary Подтвердить возврат
 */
export const useRefundControllerApprove = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refundControllerApprove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refundControllerApprove>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getRefundControllerApproveMutationOptions(options), queryClient);
    }
    /**
 * Админский эндпоинт. Меняет статус заявки на возврат на REJECTED.
 * @summary Отклонить возврат
 */
export const refundControllerReject = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/refunds/${id}/status/rejected`, method: 'PATCH', signal
    },
      options);
    }



export const getRefundControllerRejectMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refundControllerReject>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refundControllerReject>>, TError,{id: number}, TContext> => {

const mutationKey = ['refundControllerReject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refundControllerReject>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  refundControllerReject(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefundControllerRejectMutationResult = NonNullable<Awaited<ReturnType<typeof refundControllerReject>>>

    export type RefundControllerRejectMutationError = ErrorType<unknown>

    /**
 * @summary Отклонить возврат
 */
export const useRefundControllerReject = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refundControllerReject>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refundControllerReject>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getRefundControllerRejectMutationOptions(options), queryClient);
    }
