/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateWalletDto,
  UpdateWalletDto,
  WalletAdminControllerFindAllParams,
  WalletEntity
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Создаёт кошелёк. Доступно только ADMIN.
 * @summary Создать кошелёк
 */
export const walletAdminControllerCreate = (
    createWalletDto: BodyType<CreateWalletDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WalletEntity>(
      {url: `/api/admin/wallets`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWalletDto, signal
    },
      options);
    }



export const getWalletAdminControllerCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof walletAdminControllerCreate>>, TError,{data: BodyType<CreateWalletDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof walletAdminControllerCreate>>, TError,{data: BodyType<CreateWalletDto>}, TContext> => {

const mutationKey = ['walletAdminControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof walletAdminControllerCreate>>, {data: BodyType<CreateWalletDto>}> = (props) => {
          const {data} = props ?? {};

          return  walletAdminControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WalletAdminControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof walletAdminControllerCreate>>>
    export type WalletAdminControllerCreateMutationBody = BodyType<CreateWalletDto>
    export type WalletAdminControllerCreateMutationError = ErrorType<unknown>

    /**
 * @summary Создать кошелёк
 */
export const useWalletAdminControllerCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof walletAdminControllerCreate>>, TError,{data: BodyType<CreateWalletDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof walletAdminControllerCreate>>,
        TError,
        {data: BodyType<CreateWalletDto>},
        TContext
      > => {
      return useMutation(getWalletAdminControllerCreateMutationOptions(options));
    }
    /**
 * Возвращает кошельки в формате, совместимом с React Admin: list и getMany.
 * @summary Получить список кошельков
 */
export const walletAdminControllerFindAll = (
    params?: WalletAdminControllerFindAllParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WalletEntity[]>(
      {url: `/api/admin/wallets`, method: 'GET',
        params, signal
    },
      options);
    }




export const getWalletAdminControllerFindAllQueryKey = (params?: WalletAdminControllerFindAllParams,) => {
    return [
    `/api/admin/wallets`, ...(params ? [params] : [])
    ] as const;
    }


export const getWalletAdminControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof walletAdminControllerFindAll>>, TError = ErrorType<unknown>>(params?: WalletAdminControllerFindAllParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof walletAdminControllerFindAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWalletAdminControllerFindAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof walletAdminControllerFindAll>>> = ({ signal }) => walletAdminControllerFindAll(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof walletAdminControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type WalletAdminControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof walletAdminControllerFindAll>>>
export type WalletAdminControllerFindAllQueryError = ErrorType<unknown>


/**
 * @summary Получить список кошельков
 */

export function useWalletAdminControllerFindAll<TData = Awaited<ReturnType<typeof walletAdminControllerFindAll>>, TError = ErrorType<unknown>>(
 params?: WalletAdminControllerFindAllParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof walletAdminControllerFindAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWalletAdminControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const walletAdminControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WalletEntity>(
      {url: `/api/admin/wallets/${id}`, method: 'GET', signal
    },
      options);
    }




export const getWalletAdminControllerFindOneQueryKey = (id: string,) => {
    return [
    `/api/admin/wallets/${id}`
    ] as const;
    }


export const getWalletAdminControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof walletAdminControllerFindOne>>, TError = ErrorType<unknown>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof walletAdminControllerFindOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWalletAdminControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof walletAdminControllerFindOne>>> = ({ signal }) => walletAdminControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof walletAdminControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type WalletAdminControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof walletAdminControllerFindOne>>>
export type WalletAdminControllerFindOneQueryError = ErrorType<unknown>



export function useWalletAdminControllerFindOne<TData = Awaited<ReturnType<typeof walletAdminControllerFindOne>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof walletAdminControllerFindOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWalletAdminControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Обновляет кошелёк по id. Доступно только ADMIN.
 * @summary Обновить кошелёк
 */
export const walletAdminControllerUpdate = (
    id: string,
    updateWalletDto: BodyType<UpdateWalletDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WalletEntity>(
      {url: `/api/admin/wallets/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateWalletDto, signal
    },
      options);
    }



export const getWalletAdminControllerUpdateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof walletAdminControllerUpdate>>, TError,{id: string;data: BodyType<UpdateWalletDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof walletAdminControllerUpdate>>, TError,{id: string;data: BodyType<UpdateWalletDto>}, TContext> => {

const mutationKey = ['walletAdminControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof walletAdminControllerUpdate>>, {id: string;data: BodyType<UpdateWalletDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  walletAdminControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WalletAdminControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof walletAdminControllerUpdate>>>
    export type WalletAdminControllerUpdateMutationBody = BodyType<UpdateWalletDto>
    export type WalletAdminControllerUpdateMutationError = ErrorType<unknown>

    /**
 * @summary Обновить кошелёк
 */
export const useWalletAdminControllerUpdate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof walletAdminControllerUpdate>>, TError,{id: string;data: BodyType<UpdateWalletDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof walletAdminControllerUpdate>>,
        TError,
        {id: string;data: BodyType<UpdateWalletDto>},
        TContext
      > => {
      return useMutation(getWalletAdminControllerUpdateMutationOptions(options));
    }
    /**
 * Удаляет кошелёк по id. Доступно только ADMIN.
 * @summary Удалить кошелёк
 */
export const walletAdminControllerRemove = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WalletEntity>(
      {url: `/api/admin/wallets/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getWalletAdminControllerRemoveMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof walletAdminControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof walletAdminControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['walletAdminControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof walletAdminControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  walletAdminControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WalletAdminControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof walletAdminControllerRemove>>>

    export type WalletAdminControllerRemoveMutationError = ErrorType<unknown>

    /**
 * @summary Удалить кошелёк
 */
export const useWalletAdminControllerRemove = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof walletAdminControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof walletAdminControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getWalletAdminControllerRemoveMutationOptions(options));
    }
