/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ClientTypeExistDto
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Проверяет, существует ли запись типа клиента в таблице client_types.
 * @summary Проверить существование client type
 */
export const clientTypeControllerExists = (
    clientTypeExistDto: BodyType<ClientTypeExistDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/client-types/exists`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: clientTypeExistDto, signal
    },
      options);
    }



export const getClientTypeControllerExistsMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientTypeControllerExists>>, TError,{data: BodyType<ClientTypeExistDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof clientTypeControllerExists>>, TError,{data: BodyType<ClientTypeExistDto>}, TContext> => {

const mutationKey = ['clientTypeControllerExists'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clientTypeControllerExists>>, {data: BodyType<ClientTypeExistDto>}> = (props) => {
          const {data} = props ?? {};

          return  clientTypeControllerExists(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClientTypeControllerExistsMutationResult = NonNullable<Awaited<ReturnType<typeof clientTypeControllerExists>>>
    export type ClientTypeControllerExistsMutationBody = BodyType<ClientTypeExistDto>
    export type ClientTypeControllerExistsMutationError = ErrorType<void>

    /**
 * @summary Проверить существование client type
 */
export const useClientTypeControllerExists = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientTypeControllerExists>>, TError,{data: BodyType<ClientTypeExistDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clientTypeControllerExists>>,
        TError,
        {data: BodyType<ClientTypeExistDto>},
        TContext
      > => {
      return useMutation(getClientTypeControllerExistsMutationOptions(options), queryClient);
    }
