/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  UpdateUserDto,
  UserAdminControllerGetAllParams,
  UserEntity
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const userAdminControllerGetAll = (
    params?: UserAdminControllerGetAllParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserEntity[]>(
      {url: `/api/admin/users`, method: 'GET',
        params, signal
    },
      options);
    }




export const getUserAdminControllerGetAllQueryKey = (params?: UserAdminControllerGetAllParams,) => {
    return [
    `/api/admin/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getUserAdminControllerGetAllQueryOptions = <TData = Awaited<ReturnType<typeof userAdminControllerGetAll>>, TError = ErrorType<unknown>>(params?: UserAdminControllerGetAllParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userAdminControllerGetAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserAdminControllerGetAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof userAdminControllerGetAll>>> = ({ signal }) => userAdminControllerGetAll(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userAdminControllerGetAll>>, TError, TData> & { queryKey: QueryKey }
}

export type UserAdminControllerGetAllQueryResult = NonNullable<Awaited<ReturnType<typeof userAdminControllerGetAll>>>
export type UserAdminControllerGetAllQueryError = ErrorType<unknown>



export function useUserAdminControllerGetAll<TData = Awaited<ReturnType<typeof userAdminControllerGetAll>>, TError = ErrorType<unknown>>(
 params?: UserAdminControllerGetAllParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userAdminControllerGetAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUserAdminControllerGetAllQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Проверка
 * @summary Проверка на админа текущего пользователя
 */
export const userAdminControllerIsAdmin = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<boolean>(
      {url: `/api/admin/users/is-admin`, method: 'GET', signal
    },
      options);
    }




export const getUserAdminControllerIsAdminQueryKey = () => {
    return [
    `/api/admin/users/is-admin`
    ] as const;
    }


export const getUserAdminControllerIsAdminQueryOptions = <TData = Awaited<ReturnType<typeof userAdminControllerIsAdmin>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userAdminControllerIsAdmin>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserAdminControllerIsAdminQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof userAdminControllerIsAdmin>>> = ({ signal }) => userAdminControllerIsAdmin(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userAdminControllerIsAdmin>>, TError, TData> & { queryKey: QueryKey }
}

export type UserAdminControllerIsAdminQueryResult = NonNullable<Awaited<ReturnType<typeof userAdminControllerIsAdmin>>>
export type UserAdminControllerIsAdminQueryError = ErrorType<unknown>


/**
 * @summary Проверка на админа текущего пользователя
 */

export function useUserAdminControllerIsAdmin<TData = Awaited<ReturnType<typeof userAdminControllerIsAdmin>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userAdminControllerIsAdmin>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUserAdminControllerIsAdminQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Возвращает пользователя по path-параметру id.
 * @summary Получить пользователя по id
 */
export const userAdminControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserEntity>(
      {url: `/api/admin/users/${id}`, method: 'GET', signal
    },
      options);
    }




export const getUserAdminControllerFindOneQueryKey = (id: string,) => {
    return [
    `/api/admin/users/${id}`
    ] as const;
    }


export const getUserAdminControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof userAdminControllerFindOne>>, TError = ErrorType<unknown>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userAdminControllerFindOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserAdminControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof userAdminControllerFindOne>>> = ({ signal }) => userAdminControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userAdminControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type UserAdminControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof userAdminControllerFindOne>>>
export type UserAdminControllerFindOneQueryError = ErrorType<unknown>


/**
 * @summary Получить пользователя по id
 */

export function useUserAdminControllerFindOne<TData = Awaited<ReturnType<typeof userAdminControllerFindOne>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userAdminControllerFindOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUserAdminControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const userAdminControllerRemove = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserEntity>(
      {url: `/api/admin/users/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getUserAdminControllerRemoveMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userAdminControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userAdminControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['userAdminControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userAdminControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  userAdminControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UserAdminControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof userAdminControllerRemove>>>

    export type UserAdminControllerRemoveMutationError = ErrorType<unknown>

    export const useUserAdminControllerRemove = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userAdminControllerRemove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userAdminControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getUserAdminControllerRemoveMutationOptions(options));
    }
    export const userAdminControllerUpdate = (
    id: string,
    updateUserDto: BodyType<UpdateUserDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserEntity>(
      {url: `/api/admin/users/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateUserDto, signal
    },
      options);
    }



export const getUserAdminControllerUpdateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userAdminControllerUpdate>>, TError,{id: string;data: BodyType<UpdateUserDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userAdminControllerUpdate>>, TError,{id: string;data: BodyType<UpdateUserDto>}, TContext> => {

const mutationKey = ['userAdminControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userAdminControllerUpdate>>, {id: string;data: BodyType<UpdateUserDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  userAdminControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UserAdminControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof userAdminControllerUpdate>>>
    export type UserAdminControllerUpdateMutationBody = BodyType<UpdateUserDto>
    export type UserAdminControllerUpdateMutationError = ErrorType<unknown>

    export const useUserAdminControllerUpdate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userAdminControllerUpdate>>, TError,{id: string;data: BodyType<UpdateUserDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userAdminControllerUpdate>>,
        TError,
        {id: string;data: BodyType<UpdateUserDto>},
        TContext
      > => {
      return useMutation(getUserAdminControllerUpdateMutationOptions(options));
    }
