/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  XuiClient
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * ТОЛЬКО ДЛЯ ADMIN
 * @summary Получить inbound из 3x-ui
 */
export const threeXUiControllerGetInbounds = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/three-x-ui/inbounds`, method: 'GET', signal
    },
      options);
    }




export const getThreeXUiControllerGetInboundsQueryKey = () => {
    return [
    `/api/three-x-ui/inbounds`
    ] as const;
    }


export const getThreeXUiControllerGetInboundsQueryOptions = <TData = Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>, TError = ErrorType<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getThreeXUiControllerGetInboundsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>> = ({ signal }) => threeXUiControllerGetInbounds(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ThreeXUiControllerGetInboundsQueryResult = NonNullable<Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>>
export type ThreeXUiControllerGetInboundsQueryError = ErrorType<void>


export function useThreeXUiControllerGetInbounds<TData = Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>, TError = ErrorType<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>,
          TError,
          Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useThreeXUiControllerGetInbounds<TData = Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>,
          TError,
          Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useThreeXUiControllerGetInbounds<TData = Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить inbound из 3x-ui
 */

export function useThreeXUiControllerGetInbounds<TData = Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof threeXUiControllerGetInbounds>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getThreeXUiControllerGetInboundsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * ТОЛЬКО ДЛЯ ADMIN
 * @summary Добавить клиента в 3x-ui
 */
export const threeXUiControllerAddClient = (
    inboundId: number,
    xuiClient: BodyType<XuiClient>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/three-x-ui/inbounds/${inboundId}/clients`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: xuiClient, signal
    },
      options);
    }



export const getThreeXUiControllerAddClientMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof threeXUiControllerAddClient>>, TError,{inboundId: number;data: BodyType<XuiClient>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof threeXUiControllerAddClient>>, TError,{inboundId: number;data: BodyType<XuiClient>}, TContext> => {

const mutationKey = ['threeXUiControllerAddClient'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof threeXUiControllerAddClient>>, {inboundId: number;data: BodyType<XuiClient>}> = (props) => {
          const {inboundId,data} = props ?? {};

          return  threeXUiControllerAddClient(inboundId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ThreeXUiControllerAddClientMutationResult = NonNullable<Awaited<ReturnType<typeof threeXUiControllerAddClient>>>
    export type ThreeXUiControllerAddClientMutationBody = BodyType<XuiClient>
    export type ThreeXUiControllerAddClientMutationError = ErrorType<void>

    /**
 * @summary Добавить клиента в 3x-ui
 */
export const useThreeXUiControllerAddClient = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof threeXUiControllerAddClient>>, TError,{inboundId: number;data: BodyType<XuiClient>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof threeXUiControllerAddClient>>,
        TError,
        {inboundId: number;data: BodyType<XuiClient>},
        TContext
      > => {
      return useMutation(getThreeXUiControllerAddClientMutationOptions(options), queryClient);
    }
    /**
 * ТОЛЬКО ДЛЯ ADMIN
 * @summary Сбросить трафик клиента
 */
export const threeXUiControllerResetClientTraffic = (
    inboundId: number,
    email: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/three-x-ui/inbounds/${inboundId}/clients/${email}/traffic/reset`, method: 'POST', signal
    },
      options);
    }



export const getThreeXUiControllerResetClientTrafficMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof threeXUiControllerResetClientTraffic>>, TError,{inboundId: number;email: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof threeXUiControllerResetClientTraffic>>, TError,{inboundId: number;email: string}, TContext> => {

const mutationKey = ['threeXUiControllerResetClientTraffic'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof threeXUiControllerResetClientTraffic>>, {inboundId: number;email: string}> = (props) => {
          const {inboundId,email} = props ?? {};

          return  threeXUiControllerResetClientTraffic(inboundId,email,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ThreeXUiControllerResetClientTrafficMutationResult = NonNullable<Awaited<ReturnType<typeof threeXUiControllerResetClientTraffic>>>

    export type ThreeXUiControllerResetClientTrafficMutationError = ErrorType<void>

    /**
 * @summary Сбросить трафик клиента
 */
export const useThreeXUiControllerResetClientTraffic = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof threeXUiControllerResetClientTraffic>>, TError,{inboundId: number;email: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof threeXUiControllerResetClientTraffic>>,
        TError,
        {inboundId: number;email: string},
        TContext
      > => {
      return useMutation(getThreeXUiControllerResetClientTrafficMutationOptions(options), queryClient);
    }
    /**
 * ТОЛЬКО ДЛЯ ADMIN
 * @summary Удалить клиента
 */
export const threeXUiControllerDeleteClient = (
    inboundId: number,
    uuid: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/three-x-ui/inbounds/${inboundId}/clients/${uuid}`, method: 'DELETE', signal
    },
      options);
    }



export const getThreeXUiControllerDeleteClientMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof threeXUiControllerDeleteClient>>, TError,{inboundId: number;uuid: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof threeXUiControllerDeleteClient>>, TError,{inboundId: number;uuid: string}, TContext> => {

const mutationKey = ['threeXUiControllerDeleteClient'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof threeXUiControllerDeleteClient>>, {inboundId: number;uuid: string}> = (props) => {
          const {inboundId,uuid} = props ?? {};

          return  threeXUiControllerDeleteClient(inboundId,uuid,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ThreeXUiControllerDeleteClientMutationResult = NonNullable<Awaited<ReturnType<typeof threeXUiControllerDeleteClient>>>

    export type ThreeXUiControllerDeleteClientMutationError = ErrorType<void>

    /**
 * @summary Удалить клиента
 */
export const useThreeXUiControllerDeleteClient = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof threeXUiControllerDeleteClient>>, TError,{inboundId: number;uuid: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof threeXUiControllerDeleteClient>>,
        TError,
        {inboundId: number;uuid: string},
        TContext
      > => {
      return useMutation(getThreeXUiControllerDeleteClientMutationOptions(options), queryClient);
    }
