/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateReviewDto,
  ReviewEntity
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Создаёт отзыв текущего пользователя. После создания canComment автоматически становится false.
 * @summary Создать отзыв
 */
export const reviewControllerCreate = (
    createReviewDto: BodyType<CreateReviewDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewEntity>(
      {url: `/api/reviews`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createReviewDto, signal
    },
      options);
    }



export const getReviewControllerCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reviewControllerCreate>>, TError,{data: BodyType<CreateReviewDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof reviewControllerCreate>>, TError,{data: BodyType<CreateReviewDto>}, TContext> => {

const mutationKey = ['reviewControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reviewControllerCreate>>, {data: BodyType<CreateReviewDto>}> = (props) => {
          const {data} = props ?? {};

          return  reviewControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReviewControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof reviewControllerCreate>>>
    export type ReviewControllerCreateMutationBody = BodyType<CreateReviewDto>
    export type ReviewControllerCreateMutationError = ErrorType<unknown>

    /**
 * @summary Создать отзыв
 */
export const useReviewControllerCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reviewControllerCreate>>, TError,{data: BodyType<CreateReviewDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof reviewControllerCreate>>,
        TError,
        {data: BodyType<CreateReviewDto>},
        TContext
      > => {
      return useMutation(getReviewControllerCreateMutationOptions(options));
    }
    /**
 * Возвращает список всех отзывов.
 * @summary Получить все отзывы
 */
export const reviewControllerFindAll = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewEntity[]>(
      {url: `/api/reviews`, method: 'GET', signal
    },
      options);
    }




export const getReviewControllerFindAllQueryKey = () => {
    return [
    `/api/reviews`
    ] as const;
    }


export const getReviewControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof reviewControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof reviewControllerFindAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReviewControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof reviewControllerFindAll>>> = ({ signal }) => reviewControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reviewControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type ReviewControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof reviewControllerFindAll>>>
export type ReviewControllerFindAllQueryError = ErrorType<unknown>


/**
 * @summary Получить все отзывы
 */

export function useReviewControllerFindAll<TData = Awaited<ReturnType<typeof reviewControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof reviewControllerFindAll>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getReviewControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Возвращает один отзыв по его идентификатору.
 * @summary Получить отзыв по id
 */
export const reviewControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewEntity>(
      {url: `/api/reviews/${id}`, method: 'GET', signal
    },
      options);
    }




export const getReviewControllerFindOneQueryKey = (id: number,) => {
    return [
    `/api/reviews/${id}`
    ] as const;
    }


export const getReviewControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof reviewControllerFindOne>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof reviewControllerFindOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReviewControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof reviewControllerFindOne>>> = ({ signal }) => reviewControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reviewControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type ReviewControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof reviewControllerFindOne>>>
export type ReviewControllerFindOneQueryError = ErrorType<unknown>


/**
 * @summary Получить отзыв по id
 */

export function useReviewControllerFindOne<TData = Awaited<ReturnType<typeof reviewControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof reviewControllerFindOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getReviewControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Удаляет отзыв текущего пользователя. После удаления canComment автоматически становится true.
 * @summary Удалить мой отзыв
 */
export const reviewControllerRemoveMyReview = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewEntity>(
      {url: `/api/reviews/me`, method: 'DELETE', signal
    },
      options);
    }



export const getReviewControllerRemoveMyReviewMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reviewControllerRemoveMyReview>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof reviewControllerRemoveMyReview>>, TError,void, TContext> => {

const mutationKey = ['reviewControllerRemoveMyReview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reviewControllerRemoveMyReview>>, void> = () => {


          return  reviewControllerRemoveMyReview(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReviewControllerRemoveMyReviewMutationResult = NonNullable<Awaited<ReturnType<typeof reviewControllerRemoveMyReview>>>

    export type ReviewControllerRemoveMyReviewMutationError = ErrorType<unknown>

    /**
 * @summary Удалить мой отзыв
 */
export const useReviewControllerRemoveMyReview = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reviewControllerRemoveMyReview>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof reviewControllerRemoveMyReview>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getReviewControllerRemoveMyReviewMutationOptions(options));
    }
