/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Zeroquest API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePaymentDto,
  GiveBonusDto
} from '../base-api.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Создаёт платёж у провайдера YooKassa и сохраняет локальную запись в таблице payments.
 * @summary Создать платёж
 */
export const paymentControllerCreate = (
    createPaymentDto: BodyType<CreatePaymentDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/payments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPaymentDto, signal
    },
      options);
    }



export const getPaymentControllerCreateMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerCreate>>, TError,{data: BodyType<CreatePaymentDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof paymentControllerCreate>>, TError,{data: BodyType<CreatePaymentDto>}, TContext> => {

const mutationKey = ['paymentControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof paymentControllerCreate>>, {data: BodyType<CreatePaymentDto>}> = (props) => {
          const {data} = props ?? {};

          return  paymentControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PaymentControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof paymentControllerCreate>>>
    export type PaymentControllerCreateMutationBody = BodyType<CreatePaymentDto>
    export type PaymentControllerCreateMutationError = ErrorType<void>

    /**
 * @summary Создать платёж
 */
export const usePaymentControllerCreate = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerCreate>>, TError,{data: BodyType<CreatePaymentDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof paymentControllerCreate>>,
        TError,
        {data: BodyType<CreatePaymentDto>},
        TContext
      > => {
      return useMutation(getPaymentControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * Возвращает платежи текущего пользователя.
 * @summary Получить список моих платежей
 */
export const paymentControllerFindAll = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/payments`, method: 'GET', signal
    },
      options);
    }




export const getPaymentControllerFindAllQueryKey = () => {
    return [
    `/api/payments`
    ] as const;
    }


export const getPaymentControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof paymentControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentControllerFindAll>>> = ({ signal }) => paymentControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof paymentControllerFindAll>>>
export type PaymentControllerFindAllQueryError = ErrorType<unknown>


export function usePaymentControllerFindAll<TData = Awaited<ReturnType<typeof paymentControllerFindAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerFindAll<TData = Awaited<ReturnType<typeof paymentControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerFindAll<TData = Awaited<ReturnType<typeof paymentControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить список моих платежей
 */

export function usePaymentControllerFindAll<TData = Awaited<ReturnType<typeof paymentControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Админский роут. Начисляет бонус на баланс пользователя и пишет walletHistory с типом BONUS.
 * @summary Начислить бонус пользователю
 */
export const paymentControllerGiveBonus = (
    giveBonusDto: BodyType<GiveBonusDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/payments/bonuses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: giveBonusDto, signal
    },
      options);
    }



export const getPaymentControllerGiveBonusMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerGiveBonus>>, TError,{data: BodyType<GiveBonusDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof paymentControllerGiveBonus>>, TError,{data: BodyType<GiveBonusDto>}, TContext> => {

const mutationKey = ['paymentControllerGiveBonus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof paymentControllerGiveBonus>>, {data: BodyType<GiveBonusDto>}> = (props) => {
          const {data} = props ?? {};

          return  paymentControllerGiveBonus(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PaymentControllerGiveBonusMutationResult = NonNullable<Awaited<ReturnType<typeof paymentControllerGiveBonus>>>
    export type PaymentControllerGiveBonusMutationBody = BodyType<GiveBonusDto>
    export type PaymentControllerGiveBonusMutationError = ErrorType<unknown>

    /**
 * @summary Начислить бонус пользователю
 */
export const usePaymentControllerGiveBonus = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerGiveBonus>>, TError,{data: BodyType<GiveBonusDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof paymentControllerGiveBonus>>,
        TError,
        {data: BodyType<GiveBonusDto>},
        TContext
      > => {
      return useMutation(getPaymentControllerGiveBonusMutationOptions(options), queryClient);
    }
    /**
 * Открывает text/event-stream соединение с heartbeat и пользовательскими событиями по платежам.
 * @summary SSE-стрим событий платежей
 */
export const paymentControllerEvents = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/payments/events`, method: 'GET', signal
    },
      options);
    }




export const getPaymentControllerEventsQueryKey = () => {
    return [
    `/api/payments/events`
    ] as const;
    }


export const getPaymentControllerEventsQueryOptions = <TData = Awaited<ReturnType<typeof paymentControllerEvents>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentControllerEventsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentControllerEvents>>> = ({ signal }) => paymentControllerEvents(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentControllerEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentControllerEventsQueryResult = NonNullable<Awaited<ReturnType<typeof paymentControllerEvents>>>
export type PaymentControllerEventsQueryError = ErrorType<unknown>


export function usePaymentControllerEvents<TData = Awaited<ReturnType<typeof paymentControllerEvents>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerEvents>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerEvents<TData = Awaited<ReturnType<typeof paymentControllerEvents>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerEvents>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerEvents<TData = Awaited<ReturnType<typeof paymentControllerEvents>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary SSE-стрим событий платежей
 */

export function usePaymentControllerEvents<TData = Awaited<ReturnType<typeof paymentControllerEvents>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentControllerEventsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Возвращает один платёж текущего пользователя.
 * @summary Получить платёж по id
 */
export const paymentControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/payments/${id}`, method: 'GET', signal
    },
      options);
    }




export const getPaymentControllerFindOneQueryKey = (id: number,) => {
    return [
    `/api/payments/${id}`
    ] as const;
    }


export const getPaymentControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof paymentControllerFindOne>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentControllerFindOne>>> = ({ signal }) => paymentControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof paymentControllerFindOne>>>
export type PaymentControllerFindOneQueryError = ErrorType<unknown>


export function usePaymentControllerFindOne<TData = Awaited<ReturnType<typeof paymentControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerFindOne<TData = Awaited<ReturnType<typeof paymentControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerFindOne<TData = Awaited<ReturnType<typeof paymentControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить платёж по id
 */

export function usePaymentControllerFindOne<TData = Awaited<ReturnType<typeof paymentControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






