services:
  redis:
    networks:
      - insight-network
    image: redis:7
    container_name: zeroquest_redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:${REDIS_PORT:-5102}:6379"
      - "127.0.0.1:5540:5540"
    volumes:
      - redis_data:/data
  redisinsight:
    image: redis/redisinsight:latest
    network_mode: "service:redis"
    container_name: zeroquest_redisinsight
    depends_on:
      - redis
    restart: unless-stopped
volumes:
  redis_data:
networks:
  insight-network:
    driver: bridge
