/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as AuthorizedRouteRouteImport } from './routes/_authorized/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthorizedSignUpRouteImport } from './routes/_unauthorized/sign-up'
import { Route as GeneralPolicyRouteImport } from './routes/_general/policy'
import { Route as AuthorizedSessionsRouteImport } from './routes/_authorized/sessions'
import { Route as AuthorizedPaymentHistoryRouteImport } from './routes/_authorized/payment-history'
import { Route as AuthorizedMagazineRouteImport } from './routes/_authorized/magazine'
import { Route as AuthorizedDashboardRouteImport } from './routes/_authorized/dashboard'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'

const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRouteRoute = AuthorizedRouteRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedSignUpRoute = UnauthorizedSignUpRouteImport.update({
  id: '/_unauthorized/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralPolicyRoute = GeneralPolicyRouteImport.update({
  id: '/_general/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedSessionsRoute = AuthorizedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedPaymentHistoryRoute =
  AuthorizedPaymentHistoryRouteImport.update({
    id: '/payment-history',
    path: '/payment-history',
    getParentRoute: () => AuthorizedRouteRoute,
  } as any)
const AuthorizedMagazineRoute = AuthorizedMagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedDashboardRoute = AuthorizedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manual': typeof ManualRoute
  '/admin': typeof AdminAdminRoute
  '/dashboard': typeof AuthorizedDashboardRoute
  '/magazine': typeof AuthorizedMagazineRoute
  '/payment-history': typeof AuthorizedPaymentHistoryRoute
  '/sessions': typeof AuthorizedSessionsRoute
  '/policy': typeof GeneralPolicyRoute
  '/sign-up': typeof UnauthorizedSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manual': typeof ManualRoute
  '/admin': typeof AdminAdminRoute
  '/dashboard': typeof AuthorizedDashboardRoute
  '/magazine': typeof AuthorizedMagazineRoute
  '/payment-history': typeof AuthorizedPaymentHistoryRoute
  '/sessions': typeof AuthorizedSessionsRoute
  '/policy': typeof GeneralPolicyRoute
  '/sign-up': typeof UnauthorizedSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authorized': typeof AuthorizedRouteRouteWithChildren
  '/manual': typeof ManualRoute
  '/_admin/admin': typeof AdminAdminRoute
  '/_authorized/dashboard': typeof AuthorizedDashboardRoute
  '/_authorized/magazine': typeof AuthorizedMagazineRoute
  '/_authorized/payment-history': typeof AuthorizedPaymentHistoryRoute
  '/_authorized/sessions': typeof AuthorizedSessionsRoute
  '/_general/policy': typeof GeneralPolicyRoute
  '/_unauthorized/sign-up': typeof UnauthorizedSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manual'
    | '/admin'
    | '/dashboard'
    | '/magazine'
    | '/payment-history'
    | '/sessions'
    | '/policy'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manual'
    | '/admin'
    | '/dashboard'
    | '/magazine'
    | '/payment-history'
    | '/sessions'
    | '/policy'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authorized'
    | '/manual'
    | '/_admin/admin'
    | '/_authorized/dashboard'
    | '/_authorized/magazine'
    | '/_authorized/payment-history'
    | '/_authorized/sessions'
    | '/_general/policy'
    | '/_unauthorized/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthorizedRouteRoute: typeof AuthorizedRouteRouteWithChildren
  ManualRoute: typeof ManualRoute
  GeneralPolicyRoute: typeof GeneralPolicyRoute
  UnauthorizedSignUpRoute: typeof UnauthorizedSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthorized/sign-up': {
      id: '/_unauthorized/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof UnauthorizedSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_general/policy': {
      id: '/_general/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof GeneralPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized/sessions': {
      id: '/_authorized/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthorizedSessionsRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/payment-history': {
      id: '/_authorized/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof AuthorizedPaymentHistoryRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/magazine': {
      id: '/_authorized/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof AuthorizedMagazineRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/dashboard': {
      id: '/_authorized/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthorizedDashboardRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthorizedRouteRouteChildren {
  AuthorizedDashboardRoute: typeof AuthorizedDashboardRoute
  AuthorizedMagazineRoute: typeof AuthorizedMagazineRoute
  AuthorizedPaymentHistoryRoute: typeof AuthorizedPaymentHistoryRoute
  AuthorizedSessionsRoute: typeof AuthorizedSessionsRoute
}

const AuthorizedRouteRouteChildren: AuthorizedRouteRouteChildren = {
  AuthorizedDashboardRoute: AuthorizedDashboardRoute,
  AuthorizedMagazineRoute: AuthorizedMagazineRoute,
  AuthorizedPaymentHistoryRoute: AuthorizedPaymentHistoryRoute,
  AuthorizedSessionsRoute: AuthorizedSessionsRoute,
}

const AuthorizedRouteRouteWithChildren = AuthorizedRouteRoute._addFileChildren(
  AuthorizedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthorizedRouteRoute: AuthorizedRouteRouteWithChildren,
  ManualRoute: ManualRoute,
  GeneralPolicyRoute: GeneralPolicyRoute,
  UnauthorizedSignUpRoute: UnauthorizedSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
