/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthorizedRouteRouteImport } from './routes/_authorized/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthorizedSignUpRouteImport } from './routes/_unauthorized/sign-up'
import { Route as AuthorizedDashboardRouteImport } from './routes/_authorized/dashboard'

const AuthorizedRouteRoute = AuthorizedRouteRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedSignUpRoute = UnauthorizedSignUpRouteImport.update({
  id: '/_unauthorized/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedDashboardRoute = AuthorizedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthorizedDashboardRoute
  '/sign-up': typeof UnauthorizedSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthorizedDashboardRoute
  '/sign-up': typeof UnauthorizedSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authorized': typeof AuthorizedRouteRouteWithChildren
  '/_authorized/dashboard': typeof AuthorizedDashboardRoute
  '/_unauthorized/sign-up': typeof UnauthorizedSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_authorized'
    | '/_authorized/dashboard'
    | '/_unauthorized/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizedRouteRoute: typeof AuthorizedRouteRouteWithChildren
  UnauthorizedSignUpRoute: typeof UnauthorizedSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthorized/sign-up': {
      id: '/_unauthorized/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof UnauthorizedSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized/dashboard': {
      id: '/_authorized/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthorizedDashboardRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
  }
}

interface AuthorizedRouteRouteChildren {
  AuthorizedDashboardRoute: typeof AuthorizedDashboardRoute
}

const AuthorizedRouteRouteChildren: AuthorizedRouteRouteChildren = {
  AuthorizedDashboardRoute: AuthorizedDashboardRoute,
}

const AuthorizedRouteRouteWithChildren = AuthorizedRouteRoute._addFileChildren(
  AuthorizedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizedRouteRoute: AuthorizedRouteRouteWithChildren,
  UnauthorizedSignUpRoute: UnauthorizedSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
