/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthorizedRouteRouteImport } from './routes/_authorized/route'
import { Route as UnauthorizedSignUpRouteImport } from './routes/_unauthorized/sign-up'

const AuthorizedRouteRoute = AuthorizedRouteRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedSignUpRoute = UnauthorizedSignUpRouteImport.update({
  id: '/_unauthorized/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthorizedRouteRoute
  '/sign-up': typeof UnauthorizedSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthorizedRouteRoute
  '/sign-up': typeof UnauthorizedSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authorized': typeof AuthorizedRouteRoute
  '/_unauthorized/sign-up': typeof UnauthorizedSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-up'
  id: '__root__' | '/_authorized' | '/_unauthorized/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthorizedRouteRoute: typeof AuthorizedRouteRoute
  UnauthorizedSignUpRoute: typeof UnauthorizedSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthorized/sign-up': {
      id: '/_unauthorized/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof UnauthorizedSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthorizedRouteRoute: AuthorizedRouteRoute,
  UnauthorizedSignUpRoute: UnauthorizedSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
